inputs:
- name: git-repository

outputs:
- name: output
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: latest

run:
  path: git-repository/scripts/build.sh